######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 30 10:28:24 2011
######################################################################

TEMPLATE = app
TARGET = inputmethod
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += chnpanel.h clicklabel.h im.h key.h keyboard.h
SOURCES += chnpanel.cpp clicklabel.cpp im.cpp key.cpp keyboard.cpp main.cpp
RESOURCES += inputmethod.qrc
QT += sql
QT += core gui widgets
